events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Servir el frontend compilado
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # 🔀 Redirigir peticiones de Ventas al servicio interno de Kubernetes
        location /api/v1/ventas {
            proxy_pass http://backend-ventas-service.default.svc.cluster.local:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

       # 🔀 Redirigir peticiones de Despachos al servicio interno
        location /api/v1/despachos {
            proxy_pass http://backend-despachos-service.default.svc.cluster.local:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Quita el /api/v1 antes de mandarlo al backend por si Spring Boot solo escucha en /despachos
            rewrite ^/api/v1/(.*)$ /$1 break;
        }

        # 🔄 RESPALDO: Por si tu backend de despachos SÍ pide obligatoriamente el /api/v1 en el puerto 8081
        location /despachos {
            proxy_pass http://backend-despachos-service.default.svc.cluster.local:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
