apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend  # 👈 Nos quedamos con este único nombre oficial
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # Asegúrate de que apunte a tu repositorio real en ECR
        image: 921558516087.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
