name: Frontend Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_FRONTEND }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_FRONTEND }}:latest

      - name: Update kubeconfig
        run: |
          # Sintaxis corregida usando --name obligatoriamente
          aws eks update-kubeconfig --name eks-proyect-innovatech --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          # 1. Elimina el despliegue anterior que está congelado en la consola
          kubectl delete deployment frontend-app --ignore-not-found=true
          kubectl delete deployment frontend --ignore-not-found=true

          # 2. Aplica la nueva configuración limpia
          kubectl apply -f k8s/deployment.yml
          
          # 3. Fuerza el inicio inmediato del nuevo contenedor
          kubectl rollout restart deployment/frontend-nuevo
