name: Frontend Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_FRONTEND }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_FRONTEND }}:latest

      - name: Update Kubeconfig and Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-proyect-innovatech
          
          # 🔥 PASO DE LIMPIEZA: Esto borra los pods viejos con errores
          kubectl delete pods -l app=frontend-app --field-selector=status.phase!=Running
          kubectl delete pods -l app=frontend --field-selector=status.phase!=Running
          
          # Tu despliegue normal (no tocar)
          kubectl apply -f k8s/deployment.yml
          kubectl rollout restart deployment/frontend-app
